#!/bin/sh
# Since Sublime is fucking insane and can't handle symlinks for the User
# directory, we'll need to manually copy stuff over.

if [ "$(uname -s)" == "Darwin" ]
then
    SUBLIME_DIR="~/Library/Application Support/Sublime Text 3"
else
    SUBLIME_DIR="~/.config/sublime-text-3"
fi

rm -rf $ZSH/sublime/User
cp -R $SUBLIME_DIR $ZSH/sublime/User
